debug = false

[content_store]
type = 'containerd'

[cri_keychain]
enable_keychain = true
image_service_path = '/run/containerd/containerd.sock'

[pull_modes.parallel_pull_unpack]
enable = true
concurrent_download_chunk_size = "16mb"
discard_unpacked_layers = true
max_concurrent_downloads = -1
max_concurrent_downloads_per_image = 32
max_concurrent_unpacks = -1
max_concurrent_unpacks_per_image = 12

[pull_modes.parallel_pull_unpack.decompress_streams."gzip"]
path = '/usr/bin/unpigz'
args = ['-d', '-c']
