name: Bot
run-name: ðŸ¤– beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/bot
