name: Bot
run-name: ðŸ¤– beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
      - uses: ./.github/actions/bot
