name: "[CI] Auto"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: make lint-docs
  lint-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: make lint-code
  templates-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: make test
  nodeadm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: cd nodeadm && make build
  nodeadm-build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: cd nodeadm && make wasm
  nodeadm-check-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: hack/nodeadm-check-generate.sh
  nodeadm-check-vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: hack/nodeadm-check-vendor.sh
  nodeadm-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: cd nodeadm && make test
  nodeadm-test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
    - run: cd nodeadm && make test-e2e
