name: "[CI] Auto"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: read

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: make lint-docs
  lint-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: make lint-code
  templates-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: make test
  nodeadm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: cd nodeadm && make build
  nodeadm-build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: cd nodeadm && make wasm
  nodeadm-check-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: hack/nodeadm-check-generate.sh
  nodeadm-check-vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: hack/nodeadm-check-vendor.sh
  nodeadm-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: cd nodeadm && make test
  nodeadm-test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - run: cd nodeadm && make test-e2e
