name: Deploy documentation
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  mkdocs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # 6.1.0
      with:
        go-version: 'stable'
    - run: |
        pushd nodeadm && make wasm && popd
        mkdir -p ./site/assets/wasm && cp ./nodeadm/_bin/nodeadm.wasm ./site/assets/wasm/
        mkdir -p ./site/assets/javascripts && cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" ./site/assets/javascripts/
    - run: pip install mkdocs mkdocs-material
      # use the --dirty flag so that we dont purge our custom assets
    - run: mkdocs gh-deploy --dirty --no-history --force
