name: Deploy documentation
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  mkdocs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # 6.2.0
      with:
        go-version: 'stable'
    - run: |
        pushd nodeadm && make wasm && popd
        mkdir -p ./site/assets/wasm && cp ./nodeadm/_bin/nodeadm.wasm ./site/assets/wasm/
        mkdir -p ./site/assets/javascripts && cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" ./site/assets/javascripts/
    - run: pip install mkdocs mkdocs-material
      # use the --dirty flag so that we dont purge our custom assets
    - run: mkdocs gh-deploy --dirty --no-history --force
