name: "Janitor"
on:
  workflow_dispatch:
  schedule:
    # hourly at the top of the hour
    - cron: "0 * * * *"
permissions:
  id-token: write
  contents: read
jobs:
  kubetest2-sweeper:
    # disable in forks
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_JANITOR }}
      - uses: ./.github/actions/janitor/kubetest2-sweeper
        with:
          max_resource_age_duration: 3h
  ami-sweeper:
    # disable in forks
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_JANITOR }}
      - uses: ./.github/actions/janitor/ami-sweeper
        with:
          # 3 days
          max_age_seconds: 259200
