name: "Janitor"
on:
  workflow_dispatch:
  schedule:
    # hourly at the top of the hour
    - cron: "0 * * * *"
permissions:
  id-token: write
  contents: read
jobs:
  kubetest2-sweeper:
    # disable in forks
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # 5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_JANITOR }}
      - uses: ./.github/actions/janitor/kubetest2-sweeper
        with:
          max_resource_age_duration: 3h
  ami-sweeper:
    # disable in forks
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # 5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_JANITOR }}
      - uses: ./.github/actions/janitor/ami-sweeper
        with:
          # 3 days
          max_age_seconds: 259200
