name: '[Sync] Update eni-max-pods.txt'
on:
  workflow_dispatch:
  schedule:
    # once a day
    - cron: '0 0 * * *'
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  update-max-pods:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - uses: actions/checkout@v3
        with:
          repository: awslabs/amazon-eks-ami
          ref: refs/heads/master
          path: amazon-eks-ami/
      - uses: actions/checkout@v3
        with:
          repository: aws/amazon-vpc-cni-k8s
          ref: refs/heads/master
          path: amazon-vpc-cni-k8s/
      - run: |
          #!/usr/bin/env bash
          set -o errexit
          cd amazon-vpc-cni-k8s/
          make generate-limits
          cp misc/eni-max-pods.txt ../amazon-eks-ami/files/eni-max-pods.txt
      - uses: peter-evans/create-pull-request@v4
        with:
            branch: update-eni-max-pods
            path: amazon-eks-ami/
            add-paths: files/eni-max-pods.txt
            commit-message: "Update eni-max-pods.txt"
            title: "Update eni-max-pods.txt"
            body: |
              Generated by [aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s):
              ```
              make generate-limits
              ```
