name: "[Sync] Update eni-max-pods.txt"
on:
  workflow_dispatch:
  schedule:
    # once a day
    - cron: "0 0 * * *"
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  update-max-pods:
    # this workflow will always fail in forks; bail if this isn't running in the upstream
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # 4.2.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SYNC_ENI_MAX_PODS }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: awslabs/amazon-eks-ami
          ref: refs/heads/main
          path: amazon-eks-ami/
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: aws/amazon-vpc-cni-k8s
          ref: refs/heads/master
          path: amazon-vpc-cni-k8s/
      - run: |
          #!/usr/bin/env bash
          set -o errexit
          cd amazon-vpc-cni-k8s/
          make generate-limits
          cp misc/eni-max-pods.txt ../amazon-eks-ami/templates/shared/runtime/eni-max-pods.txt
          cp misc/eni-max-pods.txt ../amazon-eks-ami/nodeadm/internal/kubelet/eni-max-pods.txt
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # 7.0.8
        with:
          branch: update-eni-max-pods
          path: amazon-eks-ami/
          base: main
          add-paths: |
            templates/shared/runtime/eni-max-pods.txt
            nodeadm/internal/kubelet/eni-max-pods.txt
          commit-message: "Update eni-max-pods.txt"
          committer: "GitHub <noreply@github.com>"
          author: "GitHub <noreply@github.com>"
          labels: |
            changelog/exclude
          title: "Update eni-max-pods.txt"
          body: |
            Generated by [aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s):
            ```
            make generate-limits
            ```
