name: "[Sync] Update eni-max-pods.txt"
on:
  workflow_dispatch:
  schedule:
    # once a day
    - cron: "0 0 * * *"
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  update-max-pods:
    # this workflow will always fail in forks; bail if this isn't running in the upstream
    if: github.repository == 'awslabs/amazon-eks-ami'
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # 5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SYNC_ENI_MAX_PODS }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
        with:
          repository: awslabs/amazon-eks-ami
          ref: refs/heads/main
          path: amazon-eks-ami/
      - run: |
          #!/usr/bin/env bash
          set -o errexit
          cd amazon-eks-ami/nodeadm
          make generate-instance-info
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
        with:
          repository: aws/amazon-vpc-cni-k8s
          ref: refs/heads/master
          path: amazon-vpc-cni-k8s/
      - run: |
          #!/usr/bin/env bash
          set -o errexit
          cd amazon-vpc-cni-k8s/
          make generate-limits
          cp misc/eni-max-pods.txt ../amazon-eks-ami/templates/shared/runtime/eni-max-pods.txt
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # 8.0.0
        with:
          branch: update-eni-max-pods
          path: amazon-eks-ami/
          base: main
          add-paths: |
            templates/shared/runtime/eni-max-pods.txt
            nodeadm/internal/kubelet/instance-info.jsonl
          commit-message: "chore: update eni-max-pods.txt"
          committer: "GitHub <noreply@github.com>"
          author: "GitHub <noreply@github.com>"
          labels: |
            changelog/exclude
          title: "chore: update eni-max-pods.txt"
          body: |
            Generated by [aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s):
            ```
            make generate-limits
            ```
