---
name: 'Update Dependencies'
on:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read
jobs:
  update-deps:
    if: ${{ github.repository == 'awslabs/amazon-eks-ami' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # 5.0.2
        with:
          go-version-file: 'nodeadm/go.mod'
      - name: Update Nodeadm Dependencies
        id: update_deps
        run: |
          cd nodeadm
          make update-deps
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # 6.1.0
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          branch: dependencies/update
          base: main
          delete-branch: true
          labels: |
            changelog/exclude
          body: |
            Updating go.mod with latest dependencies.
