---
name: 'Update Dependencies'
on:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read
jobs:
  update-deps:
    if: ${{ github.repository == 'awslabs/amazon-eks-ami' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # 5.0.2
        with:
          go-version-file: 'nodeadm/go.mod'
      - name: Update Nodeadm Dependencies
        id: update_deps
        run: |
          cd nodeadm
          make update-deps
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # 7.0.1
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          branch: dependencies/update
          base: main
          delete-branch: true
          labels: |
            changelog/exclude
          body: |
            Updating go.mod with latest dependencies.
