---
name: 'Update Dependencies'
on:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read
jobs:
  update-deps:
    if: ${{ github.repository == 'awslabs/amazon-eks-ami' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # 6.1.0
        with:
          go-version-file: 'nodeadm/go.mod'
      - name: Update Nodeadm Dependencies
        id: update_deps
        run: |
          cd nodeadm
          make update-deps
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # 7.0.9
        with:
          title: "chore: update dependencies"
          commit-message: "chore: update dependencies"
          committer: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
          branch: dependencies/update
          base: main
          delete-branch: true
          labels: |
            changelog/exclude
          body: |
            Updating go.mod with latest dependencies.
